@startuml
:Mulai;
:Menu Makanan dan Minuman;
if (Pilih Kategori?) then (Makanan)
  :Makanan;
  :Pilih Makanan;
  if (Pilih Makanan?) then
    :Nasi Goreng - Rp15000;
    :Mie Goreng - Rp13000;
    :Soto Ayam - Rp18000;
    :Kembali;
  endif;
else (Minuman)
  :Minuman;
  :Pilih Minuman;
  if (Pilih Minuman?) then
    :Teh - Rp5000;
    :Kopi - Rp7000;
    :Jus - Rp10000;
    :Kembali;
  endif;
endif;
:Hitung Total Harga;
:Masukkan Jumlah Uang;
if (Uang Cukup?) then
  :Berikan Kembalian;
else
  :Tampilkan Pesan Uang Tidak Cukup;
endif;
:Menu Kembali dan Lanjut;
if (Pilih Menu?) then (Kembali)
  :Kembali;
else (Lanjut)
  :Cetak Harga;
  :Selesai;
endif;
@enduml