@startuml
:Mulai;
:Menu Makanan dan Minuman;
if (Pilih Kategori?) then
  :Makanan;
  :Pilih Makanan;
  if (Pilih Makanan?) then
    :Nasi Goreng;
    :Mie Goreng;
    :Soto Ayam;
  endif;
else
  :Minuman;
  :Pilih Minuman;
  if (Pilih Minuman?) then
    :Teh;
    :Kopi;
    :Jus;
  endif;
endif;
:Selesai;
@enduml